sudo: false

language: python

python:
  - "3.6"

# command to install dependencies
install:
  - "./tool/install"

# command to run tests
script:
- pytest
- mypy -p pydynamo
- python -m flake8 pydynamo
